#################### ROUND 50: ravilla (W) vs daweiwei (B): game 1 ####################
##### game start! #####
INPUT for daweiwei:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.341106176376343s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 50 GAMESCORE AFTER GAME 1: ravilla=1 and daweiwei=0 ##########
#################### ROUND 50: ravilla (B) vs daweiwei (W): game 2 ####################
##### game start! #####
INPUT for ravilla:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" ./homework > stulog.txt 2>&1 on ravilla #####
##### SUCCESS: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" ./homework > stulog.txt 2>&1 on ravilla #####
##### ravilla plays [E b6 a5] in 0.01s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
INPUT for daweiwei:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
b.......
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.353605985641479s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 50 GAMESCORE AFTER GAME 2: ravilla=2 and daweiwei=0 ##########
#################### ROUND 50: ravilla (W) vs daweiwei (B): game 3 ####################
##### game start! #####
INPUT for daweiwei:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.328638076782227s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 50 GAMESCORE AFTER GAME 3: ravilla=3 and daweiwei=0 ##########
#################### ROUND 50: ravilla (B) vs daweiwei (W): game 4 ####################
##### game start! #####
INPUT for ravilla:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" ./homework > stulog.txt 2>&1 on ravilla #####
##### SUCCESS: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" ./homework > stulog.txt 2>&1 on ravilla #####
##### ravilla plays [E b6 a5] in 0.01s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
INPUT for daweiwei:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
b.......
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_50_ravilla_daweiwei.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.321044921875s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_daweiwei #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 50 GAMESCORE AFTER GAME 4: ravilla=4 and daweiwei=0 ##########


########## GRAND WINNER ROUND 50 IS ravilla BY 4 vs 0 GAMESCORE ##########
