#################### ROUND 2: jwang175 (B) vs mohithra (W): game 1 ####################
##### game start! #####
INPUT for jwang175:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on jwang175 #####
##### SUCCESS: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on jwang175 #####
##### jwang175 plays [E b6 c5 ] in 2.57s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
INPUT for mohithra:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
..b.....
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.403957843780518s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 1: jwang175=1 and mohithra=0 ##########
#################### ROUND 2: jwang175 (W) vs mohithra (B): game 2 ####################
##### game start! #####
INPUT for mohithra:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.379417896270752s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 2: jwang175=2 and mohithra=0 ##########
#################### ROUND 2: jwang175 (B) vs mohithra (W): game 3 ####################
##### game start! #####
INPUT for jwang175:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on jwang175 #####
##### SUCCESS: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on jwang175 #####
##### jwang175 plays [E b6 c5 ] in 2.52s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
INPUT for mohithra:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
..b.....
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.340404033660889s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 3: jwang175=3 and mohithra=0 ##########
#################### ROUND 2: jwang175 (W) vs mohithra (B): game 4 ####################
##### game start! #####
INPUT for mohithra:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_jwang175_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.32520604133606s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_jwang175_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 4: jwang175=4 and mohithra=0 ##########


########## GRAND WINNER ROUND 2 IS jwang175 BY 4 vs 0 GAMESCORE ##########
