#################### ROUND 2: daweiwei (B) vs neetukum (W): game 1 ####################
##### game start! #####
INPUT for daweiwei:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.443305015563965s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 1: daweiwei=0 and neetukum=1 ##########
#################### ROUND 2: daweiwei (W) vs neetukum (B): game 2 ####################
##### game start! #####
INPUT for neetukum:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on neetukum #####
##### SUCCESS: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on neetukum #####
##### neetukum plays [E d6 c5] in 0.17s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
INPUT for daweiwei:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
.b...b.b
..b.....
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.386308908462524s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 2: daweiwei=0 and neetukum=2 ##########
#################### ROUND 2: daweiwei (B) vs neetukum (W): game 3 ####################
##### game start! #####
INPUT for daweiwei:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.391002893447876s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 3: daweiwei=0 and neetukum=3 ##########
#################### ROUND 2: daweiwei (W) vs neetukum (B): game 4 ####################
##### game start! #####
INPUT for neetukum:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on neetukum #####
##### SUCCESS: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on neetukum #####
##### neetukum plays [E b6 c5] in 0.18s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
INPUT for daweiwei:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
..b.....
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_daweiwei_neetukum.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.306108951568604s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_neetukum #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 4: daweiwei=0 and neetukum=4 ##########


########## GRAND WINNER ROUND 2 IS neetukum BY 4 vs 0 GAMESCORE ##########
