#################### ROUND 2: daweiwei (W) vs kojoseph (B): game 1 ####################
##### game start! #####
INPUT for kojoseph:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on kojoseph #####
##### SUCCESS: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on kojoseph #####
##### kojoseph plays [E f6 e5] in 0.06s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
INPUT for daweiwei:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
.b.b...b
....b...
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.381630897521973s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 1: daweiwei=0 and kojoseph=1 ##########
#################### ROUND 2: daweiwei (B) vs kojoseph (W): game 2 ####################
##### game start! #####
INPUT for daweiwei:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.319586038589478s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 2: daweiwei=0 and kojoseph=2 ##########
#################### ROUND 2: daweiwei (W) vs kojoseph (B): game 3 ####################
##### game start! #####
INPUT for kojoseph:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on kojoseph #####
##### SUCCESS: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on kojoseph #####
##### kojoseph plays [E f6 e5] in 0.06s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
INPUT for daweiwei:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
.b.b...b
....b...
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.348620891571045s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 3: daweiwei=0 and kojoseph=3 ##########
#################### ROUND 2: daweiwei (B) vs kojoseph (W): game 4 ####################
##### game start! #####
INPUT for daweiwei:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_daweiwei_kojoseph.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on daweiwei #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 279, in <module>
    g.setUp()
  File "homework.py", line 21, in setUp
    for line in open("input1.txt"):  # .readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'input1.txt'
##### End of output of failed program #####
##### daweiwei plays [No Move] in 0.325353860855103s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_daweiwei_kojoseph #####
Game server reported error. Assuming bogus move.
##### GAME OVER: daweiwei loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 4: daweiwei=0 and kojoseph=4 ##########


########## GRAND WINNER ROUND 2 IS kojoseph BY 4 vs 0 GAMESCORE ##########
